// Generated by scripts/pro-meta-snapshot.js — do not edit by hand
const PRO_META = {
  "tournament": "Esports World Cup 2026",
  "leagueId": 19785,
  "snapshotDate": "2026-07-19",
  "games": 154,
  "heroes": {
    "2": {
      "picks": 35,
      "bans": 52,
      "wins": 14
    },
    "3": {
      "picks": 44,
      "bans": 59,
      "wins": 24
    },
    "4": {
      "picks": 2,
      "bans": 0,
      "wins": 1
    },
    "5": {
      "picks": 3,
      "bans": 0,
      "wins": 0
    },
    "6": {
      "picks": 36,
      "bans": 87,
      "wins": 15
    },
    "7": {
      "picks": 7,
      "bans": 3,
      "wins": 6
    },
    "8": {
      "picks": 2,
      "bans": 1,
      "wins": 1
    },
    "9": {
      "picks": 25,
      "bans": 5,
      "wins": 13
    },
    "10": {
      "picks": 3,
      "bans": 1,
      "wins": 1
    },
    "11": {
      "picks": 37,
      "bans": 98,
      "wins": 23
    },
    "12": {
      "picks": 8,
      "bans": 7,
      "wins": 5
    },
    "13": {
      "picks": 34,
      "bans": 76,
      "wins": 11
    },
    "14": {
      "picks": 4,
      "bans": 1,
      "wins": 1
    },
    "15": {
      "picks": 2,
      "bans": 4,
      "wins": 2
    },
    "16": {
      "picks": 2,
      "bans": 1,
      "wins": 1
    },
    "17": {
      "picks": 22,
      "bans": 20,
      "wins": 7
    },
    "18": {
      "picks": 5,
      "bans": 1,
      "wins": 3
    },
    "19": {
      "picks": 31,
      "bans": 45,
      "wins": 16
    },
    "20": {
      "picks": 0,
      "bans": 1,
      "wins": 0
    },
    "21": {
      "picks": 42,
      "bans": 30,
      "wins": 16
    },
    "22": {
      "picks": 6,
      "bans": 4,
      "wins": 2
    },
    "23": {
      "picks": 4,
      "bans": 6,
      "wins": 2
    },
    "25": {
      "picks": 18,
      "bans": 15,
      "wins": 14
    },
    "26": {
      "picks": 8,
      "bans": 6,
      "wins": 6
    },
    "27": {
      "picks": 3,
      "bans": 1,
      "wins": 3
    },
    "28": {
      "picks": 19,
      "bans": 14,
      "wins": 14
    },
    "29": {
      "picks": 7,
      "bans": 13,
      "wins": 3
    },
    "30": {
      "picks": 12,
      "bans": 5,
      "wins": 6
    },
    "31": {
      "picks": 19,
      "bans": 4,
      "wins": 11
    },
    "32": {
      "picks": 0,
      "bans": 1,
      "wins": 0
    },
    "33": {
      "picks": 19,
      "bans": 29,
      "wins": 9
    },
    "35": {
      "picks": 4,
      "bans": 7,
      "wins": 1
    },
    "36": {
      "picks": 22,
      "bans": 35,
      "wins": 12
    },
    "37": {
      "picks": 2,
      "bans": 1,
      "wins": 1
    },
    "38": {
      "picks": 31,
      "bans": 48,
      "wins": 12
    },
    "39": {
      "picks": 2,
      "bans": 4,
      "wins": 0
    },
    "40": {
      "picks": 1,
      "bans": 0,
      "wins": 0
    },
    "41": {
      "picks": 2,
      "bans": 4,
      "wins": 1
    },
    "43": {
      "picks": 1,
      "bans": 1,
      "wins": 0
    },
    "46": {
      "picks": 5,
      "bans": 8,
      "wins": 2
    },
    "47": {
      "picks": 12,
      "bans": 43,
      "wins": 1
    },
    "48": {
      "picks": 2,
      "bans": 0,
      "wins": 0
    },
    "49": {
      "picks": 1,
      "bans": 2,
      "wins": 0
    },
    "50": {
      "picks": 2,
      "bans": 0,
      "wins": 2
    },
    "51": {
      "picks": 58,
      "bans": 31,
      "wins": 25
    },
    "52": {
      "picks": 3,
      "bans": 2,
      "wins": 1
    },
    "53": {
      "picks": 16,
      "bans": 53,
      "wins": 11
    },
    "54": {
      "picks": 9,
      "bans": 15,
      "wins": 4
    },
    "55": {
      "picks": 29,
      "bans": 67,
      "wins": 19
    },
    "56": {
      "picks": 19,
      "bans": 18,
      "wins": 12
    },
    "57": {
      "picks": 4,
      "bans": 1,
      "wins": 1
    },
    "58": {
      "picks": 15,
      "bans": 19,
      "wins": 4
    },
    "59": {
      "picks": 3,
      "bans": 47,
      "wins": 3
    },
    "60": {
      "picks": 7,
      "bans": 13,
      "wins": 3
    },
    "61": {
      "picks": 2,
      "bans": 1,
      "wins": 0
    },
    "63": {
      "picks": 1,
      "bans": 0,
      "wins": 0
    },
    "64": {
      "picks": 9,
      "bans": 1,
      "wins": 5
    },
    "65": {
      "picks": 17,
      "bans": 12,
      "wins": 7
    },
    "66": {
      "picks": 1,
      "bans": 2,
      "wins": 0
    },
    "67": {
      "picks": 10,
      "bans": 27,
      "wins": 7
    },
    "68": {
      "picks": 1,
      "bans": 3,
      "wins": 1
    },
    "69": {
      "picks": 24,
      "bans": 65,
      "wins": 9
    },
    "70": {
      "picks": 2,
      "bans": 4,
      "wins": 1
    },
    "71": {
      "picks": 2,
      "bans": 0,
      "wins": 1
    },
    "72": {
      "picks": 6,
      "bans": 6,
      "wins": 2
    },
    "73": {
      "picks": 13,
      "bans": 8,
      "wins": 8
    },
    "74": {
      "picks": 24,
      "bans": 40,
      "wins": 15
    },
    "75": {
      "picks": 3,
      "bans": 3,
      "wins": 1
    },
    "77": {
      "picks": 15,
      "bans": 24,
      "wins": 10
    },
    "78": {
      "picks": 2,
      "bans": 2,
      "wins": 0
    },
    "79": {
      "picks": 3,
      "bans": 4,
      "wins": 1
    },
    "80": {
      "picks": 20,
      "bans": 131,
      "wins": 12
    },
    "82": {
      "picks": 0,
      "bans": 1,
      "wins": 0
    },
    "83": {
      "picks": 15,
      "bans": 137,
      "wins": 10
    },
    "84": {
      "picks": 2,
      "bans": 0,
      "wins": 1
    },
    "85": {
      "picks": 37,
      "bans": 55,
      "wins": 23
    },
    "86": {
      "picks": 19,
      "bans": 7,
      "wins": 11
    },
    "87": {
      "picks": 10,
      "bans": 2,
      "wins": 4
    },
    "88": {
      "picks": 3,
      "bans": 0,
      "wins": 0
    },
    "89": {
      "picks": 3,
      "bans": 7,
      "wins": 1
    },
    "90": {
      "picks": 33,
      "bans": 75,
      "wins": 20
    },
    "91": {
      "picks": 5,
      "bans": 15,
      "wins": 3
    },
    "92": {
      "picks": 1,
      "bans": 0,
      "wins": 1
    },
    "93": {
      "picks": 1,
      "bans": 1,
      "wins": 1
    },
    "94": {
      "picks": 1,
      "bans": 1,
      "wins": 0
    },
    "96": {
      "picks": 38,
      "bans": 51,
      "wins": 21
    },
    "97": {
      "picks": 0,
      "bans": 1,
      "wins": 0
    },
    "98": {
      "picks": 11,
      "bans": 15,
      "wins": 5
    },
    "99": {
      "picks": 1,
      "bans": 5,
      "wins": 1
    },
    "100": {
      "picks": 21,
      "bans": 9,
      "wins": 8
    },
    "101": {
      "picks": 1,
      "bans": 1,
      "wins": 0
    },
    "104": {
      "picks": 0,
      "bans": 1,
      "wins": 0
    },
    "105": {
      "picks": 12,
      "bans": 10,
      "wins": 5
    },
    "106": {
      "picks": 46,
      "bans": 57,
      "wins": 28
    },
    "107": {
      "picks": 66,
      "bans": 38,
      "wins": 33
    },
    "108": {
      "picks": 11,
      "bans": 16,
      "wins": 4
    },
    "109": {
      "picks": 13,
      "bans": 23,
      "wins": 4
    },
    "110": {
      "picks": 5,
      "bans": 9,
      "wins": 2
    },
    "111": {
      "picks": 5,
      "bans": 2,
      "wins": 1
    },
    "112": {
      "picks": 31,
      "bans": 19,
      "wins": 20
    },
    "114": {
      "picks": 10,
      "bans": 11,
      "wins": 5
    },
    "119": {
      "picks": 37,
      "bans": 6,
      "wins": 17
    },
    "120": {
      "picks": 17,
      "bans": 17,
      "wins": 7
    },
    "121": {
      "picks": 8,
      "bans": 1,
      "wins": 2
    },
    "123": {
      "picks": 66,
      "bans": 39,
      "wins": 37
    },
    "126": {
      "picks": 3,
      "bans": 4,
      "wins": 1
    },
    "128": {
      "picks": 34,
      "bans": 35,
      "wins": 12
    },
    "129": {
      "picks": 1,
      "bans": 5,
      "wins": 0
    },
    "131": {
      "picks": 37,
      "bans": 8,
      "wins": 16
    },
    "135": {
      "picks": 6,
      "bans": 14,
      "wins": 3
    },
    "136": {
      "picks": 1,
      "bans": 1,
      "wins": 1
    },
    "137": {
      "picks": 3,
      "bans": 1,
      "wins": 1
    },
    "138": {
      "picks": 5,
      "bans": 9,
      "wins": 2
    },
    "145": {
      "picks": 19,
      "bans": 53,
      "wins": 13
    },
    "155": {
      "picks": 38,
      "bans": 52,
      "wins": 21
    }
  }
};
